apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aljleemnt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aljleemnt-go 
  name: aljleemnt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aljleemnt-go 
