apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: aljleemnt-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:390936bf9f2c1b35ade2c2eb350a8a9d2fccfe39@sha256:bdfd65ed5d3c377187e81e170e4c30cd32954918b8958466b508a4b9aeaff7d6
          name: container-image
